### ISSUE TITLE
Broken grid system

### ISSUE THREAD

**Issue by magnusewe** [cyberchimps/responsive#25]
The theme is great but I believe the grid system is broken. I think this is needed:

``` css
@media screen and (max-width: 980px) {
    .grid, .grid-right {
        display: block;
        width: 100%;
    }
}
```
